name: carbon_supplychain
version: '1.0'
config-version: 2

profile: carbon_supplychain

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  carbon_supplychain:
    +materialized: view